### ISSUE TITLE
Sir, will you be able to help me add bots to the channels ? https://3reo.com ?

### ISSUE THREAD

**Issue by antonpictures** [Supinic/supibot#4]
Hello Sir. My name is George Anton, I currently work as a security guuard in Culver City, California. I'm a regular guy, paycheck to paycjheck. I paypal-ed to Xaetai, his real name Donald,  a cytube contributor $100 to install cytube on my AWS account with few modifications like in the attached pics below. After a basic install, the dude got corona, or something happened I don't know, he dissapeared with the money and everything. Left me with the unfinished website https://3reo.com  :) Sir, will you be able to help me add bots to the channels they are listed on the main page and to add the screen on the main page so a regular user can just change the channels like regular tv?  https://3reo.com interface to look like below?  
main page: https://i.imgur.com/q8cQy7g.jpg
admin page: https://i.imgur.com/hbQFtn7.jpg
feel free to call me anytime.
thanks a million,

George Anton
Los Angeles
310-927-9552

**Comment by whitesockies** [comment]
Pffft, bro.....

**Comment by Supinic** [comment]
Unrelated to the project.
