### ISSUE TITLE
Sending links by reminder in a channel with disabled-links option causes the bot to send a link.

### ISSUE THREAD

**Issue by derLesh** [Supinic/supibot#45]
If a channel has the "disable-links" option enabled, and you send a user in that channel a reminder with a URL in it, the bot will mention that it is not allowed to post links, but then link to the relay page.

It is pretty easy to recreate this behavior: 

![image](https://github.com/Supinic/supibot/assets/11671272/f783021d-7458-42d8-8c15-c65b615c26e4)

![image](https://github.com/Supinic/supibot/assets/11671272/43633e4e-b8a7-433d-9912-265b030a1036)

**Comment by Supinic** [comment]
Fixed in supinic/supi-core@8b14ecfb77a1ecf32497803427728e74e1b0754d
