### ISSUE TITLE
Update documentation to respect missing `user:manage:whispers` scope of twitchapps.com

### ISSUE THREAD

**Issue by Wissididom** [Supinic/supibot#49]
I was able to set up my own Supibot instance, but whispers didn't work (I was able to solve it, more below).

The first problem I had was that `Self_ID` was not set in the DB, which caused an error that `from_user_id` was not set for whispers.
Then I had the problem of a missing scope `user:manage:whispers` because the [linked token generator](https://twitchapps.com/tmi/) did only have the scopes `chat:read+chat:edit+channel:moderate+whispers:read+whispers:edit+channel_editor` which did not contain `user:manage:whispers` (which I than added through `Inspect Element`).
After that, I made the mistake that I generated the token for the wrong account (my main instead of the bot)
After that, whispers worked.

So I see 2 ways to solve this:
- Update the Markdown files that link to the page (I currently only see it needing to be adjusted in the [Setup page](https://github.com/Supinic/supibot/blob/master/docs/setup.md)) to e.g. https://twitchtokengenerator.com/
- Contact the owners of twitchapps.com to update their scopes

Since I fixed it myself, I don't really care about it being documented, but I think it might help others that might have the same issue because I needed quite some time to find out what the problem was because I didn't know about the `chat_data.Log` table (I used the interactive guide) and only found it by looking through the code (of supi-core iirc).

**Comment by Wissididom** [comment]
I'll close this again as the page does not have anything to do with the bot and it is just a suggestion that even works for normal chatting (except Whispers and `$vanish` from what I can tell rn)

**Comment by Supinic** [comment]
Fair enough, however I might as well add a mention of this into the setup guide.
