### ISSUE TITLE
[Request] Option to set custom cooldowns on commands

### ISSUE THREAD

**Issue by ejaandersson** [Supinic/supibot#54]
More or less title. If a general option is made for this, I am specifically looking for something to change cooldown on $fill.

I suspect there might already be something like this, but I looked through docs and code (I'm not great at JS though) and can't find a command to change it.

**Comment by Supinic** [comment]
(Base) cooldowns can be partially changed via the `$ban type:cooldown` command - you can set a multiplier by which the base cooldown will be made longer. The multiplier naturally cannot be set below 1. 

You can find this info in the FAQ command (`$faq`) I believe - if you have any ideas how to increase the visibility of this info, I'd definitely consider adding them! In that case, create a new issue though.
